Some stuff happening
["2 * 3 + ( 4 * 5 )", "5 + ( 8 * 3 + 9 + 3 * 4 * 3 )", "5 * 9 * ( 7 * 3 * 3 + 9 * 3 + ( 8 + 6 * 4 ) )", "( ( 2 + 4 * 9 ) * ( 6 + 9 * 8 + 6 ) + 6 ) + 2 + 4 * 2"]
([Some(2)], [])
([Some(2)], [Some(Mult)])
([Some(6)], [])
([Some(6)], [Some(Add)])
([Some(6), None], [Some(Add)])
thread 'main' panicked at 'something's missing: (Some(Some(Add)), Some(None))', src/main.rs:49:47