Further
["2 * 3 + ( 4 * 5 )", "5 + ( 8 * 3 + 9 + 3 * 4 * 3 )", "5 * 9 * ( 7 * 3 * 3 + 9 * 3 + ( 8 + 6 * 4 ) )", "( ( 2 + 4 * 9 ) * ( 6 + 9 * 8 + 6 ) + 6 ) + 2 + 4 * 2"]
2 | ([Some(2)], [])
* | ([Some(2)], [Some(Mult)])
3 | ([Some(6)], [])
+ | ([Some(6)], [Some(Add)])
( | ([Some(6), None], [Some(Add), None])
4 | ([Some(6), Some(4)], [Some(Add)])
* | ([Some(6), Some(4)], [Some(Add), Some(Mult)])
5 | ([Some(6), Some(20)], [Some(Add)])
) | ([Some(6), None], [])
5 | ([Some(5)], [])
+ | ([Some(5)], [Some(Add)])
( | ([Some(5), None], [Some(Add), None])
8 | ([Some(5), Some(8)], [Some(Add)])
* | ([Some(5), Some(8)], [Some(Add), Some(Mult)])
3 | ([Some(5), Some(24)], [Some(Add)])
+ | ([Some(5), Some(24)], [Some(Add), Some(Add)])
9 | ([Some(5), Some(33)], [Some(Add)])
+ | ([Some(5), Some(33)], [Some(Add), Some(Add)])
3 | ([Some(5), Some(36)], [Some(Add)])
* | ([Some(5), Some(36)], [Some(Add), Some(Mult)])
4 | ([Some(5), Some(144)], [Some(Add)])
* | ([Some(5), Some(144)], [Some(Add), Some(Mult)])
3 | ([Some(5), Some(432)], [Some(Add)])
) | ([Some(5), None], [])
5 | ([Some(5)], [])
* | ([Some(5)], [Some(Mult)])
9 | ([Some(45)], [])
* | ([Some(45)], [Some(Mult)])
( | ([Some(45), None], [Some(Mult), None])
7 | ([Some(45), Some(7)], [Some(Mult)])
* | ([Some(45), Some(7)], [Some(Mult), Some(Mult)])
3 | ([Some(45), Some(21)], [Some(Mult)])
* | ([Some(45), Some(21)], [Some(Mult), Some(Mult)])
3 | ([Some(45), Some(63)], [Some(Mult)])
+ | ([Some(45), Some(63)], [Some(Mult), Some(Add)])
9 | ([Some(45), Some(72)], [Some(Mult)])
* | ([Some(45), Some(72)], [Some(Mult), Some(Mult)])
3 | ([Some(45), Some(216)], [Some(Mult)])
+ | ([Some(45), Some(216)], [Some(Mult), Some(Add)])
( | ([Some(45), Some(216), None], [Some(Mult), Some(Add), None])
8 | ([Some(45), Some(216), Some(8)], [Some(Mult), Some(Add)])
+ | ([Some(45), Some(216), Some(8)], [Some(Mult), Some(Add), Some(Add)])
6 | ([Some(45), Some(216), Some(14)], [Some(Mult), Some(Add)])
* | ([Some(45), Some(216), Some(14)], [Some(Mult), Some(Add), Some(Mult)])
4 | ([Some(45), Some(216), Some(56)], [Some(Mult), Some(Add)])
) | ([Some(45), Some(216), None], [Some(Mult)])
) | ([Some(45), Some(216), None], [])
( | ([None, None], [None, None])
( | ([None, None, None], [None, None, None])
2 | ([None, None, Some(2)], [None, None])
+ | ([None, None, Some(2)], [None, None, Some(Add)])
4 | ([None, None, Some(6)], [None, None])
* | ([None, None, Some(6)], [None, None, Some(Mult)])
9 | ([None, None, Some(54)], [None, None])
) | ([None, None, None], [None])
* | ([None, None, None], [None, Some(Mult)])
( | ([None, None, None, None], [None, Some(Mult), None])
6 | ([None, None, None, Some(6)], [None, Some(Mult)])
+ | ([None, None, None, Some(6)], [None, Some(Mult), Some(Add)])
9 | ([None, None, None, Some(15)], [None, Some(Mult)])
* | ([None, None, None, Some(15)], [None, Some(Mult), Some(Mult)])
8 | ([None, None, None, Some(120)], [None, Some(Mult)])
+ | ([None, None, None, Some(120)], [None, Some(Mult), Some(Add)])
6 | ([None, None, None, Some(126)], [None, Some(Mult)])
) | ([None, None, None, None], [None])
+ | ([None, None, None, None], [None, Some(Add)])
thread 'main' panicked at 'something's missing: (Some(Some(Add)), Some(None))', src/main.rs:52:47